[font]
size = 16.0

[font.normal]
family = "Hack Nerd Font Mono"

# Gnome Terminal Theme
# https://github.com/alacritty/alacritty-theme/blob/master/themes/gnome_terminal.toml

[colors.primary]
background = '#1e1e1e'
foreground = '#ffffff'

[colors.normal]
black      = '#171421'
red        = '#c01c28'
green      = '#26a269'
yellow     = '#a2734c'
blue       = '#12488b'
magenta    = '#a347ba'
cyan       = '#2aa1b3'
white      = '#d0cfcc'

[colors.bright]
black      = '#5e5c64'
red        = '#f66151'
green      = '#33d17a'
yellow     = '#e9ad0c'
blue       = '#2a7bde'
magenta    = '#c061cb'
cyan       = '#33c7de'
white      = '#ffffff'